pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Configure RayNeo private Maven server
        /*maven {
            url 'http://172.16.46.52:9998/repository/maven-public/'
            allowInsecureProtocol = true
        }*/
    }
}
rootProject.name = "MercuryAndroidSDK"
include ':app'

