plugins {
    id 'com.android.application'
}

android {
    compileSdk = 34

    defaultConfig {
        applicationId = "com.ffalcon.mercury.android.sdk"
        minSdk = 31
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        create("xr2") {
            storeFile = file("$rootDir/xr2-platform.jks")
            storePassword = "android"
            keyAlias =  "platform"
            keyPassword =  "android"
        }
    }
    buildTypes {

        debug {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("xr2")
        }

        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("xr2")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
        }
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
    namespace = 'com.ffalcon.mercury.android.sdk.demo'
}

dependencies {
    implementation(fileTree("libs"))
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
    implementation 'androidx.fragment:fragment-ktx:1.5.3'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'com.tencent.tav:libpag:4.3.62'
}